# Generated by Django 6.0.5 on 2026-05-18 15:28

import Movies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('image', models.ImageField(upload_to='movies/')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cast', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True, validators=[Movies.models.validate_youtube_url])),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='Movies.genre')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='Movies.language')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('price', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.movie')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Movies.seat')),
            ],
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='Movies.seat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('time', models.DateTimeField(db_index=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='Movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='Movies.theater'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=255, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seats_data', models.JSONField(default=list)),
                ('idempotency_key', models.UUIDField(editable=False, unique=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Movies.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('theater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Movies.theater')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.theater'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='Movies_movi_name_7a4bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='Movies_movi_rating_7f0f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language'], name='Movies_movi_languag_a99c80_idx'),
        ),
        migrations.AddConstraint(
            model_name='seatreservation',
            constraint=models.UniqueConstraint(fields=('seat',), name='unique_active_seat_reservation'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['time'], name='Movies_thea_time_01ed70_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['movie'], name='Movies_thea_movie_i_818118_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='Movies_paym_status_24017b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='Movies_paym_created_1233e8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='Movies_book_booked__f754a4_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie'], name='Movies_book_movie_i_212cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater'], name='Movies_book_theater_3608ef_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='Movies_book_user_id_eb3473_idx'),
        ),
    ]
