# Generated by Django 6.0.5 on 2026-05-13 21:32

import Movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, validators=[Movies.models.validate_youtube_url]),
        ),
    ]
