# Generated by Django 6.0.5 on 2026-05-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_movie_trailer_url'),
        ('Movies', '0003_booking_price_payment_seatreservation'),
    ]

    operations = [
    ]
