# Generated by Django 6.0.5 on 2026-05-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0006_genre_language'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['rating'], name='Movies_movi_rating_7f0f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language'], name='Movies_movi_languag_a99c80_idx'),
        ),
    ]
